name: CI

on: push

jobs:
  test:
    name: CI

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: NPM Install
        run: npm ci --ignore-scripts --prefer-offline --legacy-peer-deps
      - name: Run Cypress Postinstall Script
        run: npm run cypress:install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - uses: codecov/codecov-action@v2
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
